empty = -1
black = 1
white = 0
size = 9
width = 540
height = 540
margin = 22
grid = (width - 2 * margin) / (size - 1)
feature_planes = 6
piece = 34
n_iters = 2000
modelpath = '../model/' + "model_{}.pth".format(size, size)
boardpath = 'img/chessboard_{}.jpg'.format(size)
